server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
zuul:
  prefix: /techouse
  routes: 
    service-hi:
      path: /usersystem/**
      serviceId: service-hi
      
ribbon:
  eureka:
    enabled: false

service-hi:
  ribbon:
    listOfServers: 127.0.0.1:8800
